-- 0008_suprema_profiles.sql
-- Extração real do catálogo de perfis Tec-Vidro (fonte técnica 4), 41 perfis.
--
-- ACHADO IMPORTANTE DA EXTRAÇÃO: a palavra "Suprema" NÃO aparece em nenhuma das
-- 10 páginas do PDF. O catálogo se identifica apenas como linha "TEC-SUP" e usa o
-- prefixo "SU" nos códigos de perfil. O nome "Suprema" veio do enunciado original
-- da tarefa, não da fonte — por isso corrigimos a linha/fonte para refletir
-- honestamente essa lacuna, sem deixar de manter o nome comercial dado pelo
-- usuário como referência (campo `code` da linha continua SUPREMA para não
-- quebrar a rastreabilidade com o pedido original).
UPDATE product_lines
SET description = 'Linha identificada no catálogo como "TEC-SUP" (perfis com prefixo SU). O nome comercial "Suprema" foi usado no pedido original mas NÃO aparece escrito em nenhuma das 10 páginas do PDF-fonte — tratar como não confirmado textualmente até checar com o fabricante ou outra fonte.',
    origin_type = 'ENCONTRADO_DOCUMENTO',
    status_code = 'NECESSITA_CONFERENCIA'
WHERE id = 6;

UPDATE technical_sources
SET title = 'Catálogo de Perfis Tec-Vidro "TEC-SUP" (linha referida como Suprema no pedido original)',
    notes = 'Extração concluída: 41 perfis (P-1249 a P-1288 + P-1303 fora de sequência), 10/10 páginas lidas. Sem coluna de aplicação em nenhum perfil. Sem segmentação "revenda"/"fachada cortina" no documento (ver docs/FONTES.md). Condição comercial isolada p.9: pedido mínimo 300kg, barras de 6m — aplicabilidade (todos os perfis ou só os da página) não está clara no texto.'
WHERE id = 4;

-- Perfis (código primário = SU-xxx; código interno do fabricante P-xxxx preservado na descrição)
INSERT INTO source_references (technical_source_id, page_number, extracted_by) VALUES (4, 2, 'agent-extraction');
SET @ref_4_2 = LAST_INSERT_ID();
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-001', 'Perfil SU 001', 'OUTRO', 0.714, 'Código interno do fabricante: P-1249. Dimensões(raw): 71,0 (largura sup.); 17,0 (altura dir.); 33,0 (altura esq., cota parcial). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_2);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-002', 'Perfil SU 002', 'OUTRO', 0.643, 'Código interno do fabricante: P-1303. Dimensões(raw): 71,0 (largura inf.); 47,0 (altura dir.); 33,0 (altura esq.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_2);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-003', 'Perfil SU 003', 'OUTRO', 0.469, 'Código interno do fabricante: P-1250. Dimensões(raw): 71,0 (largura); 26,0 (altura esq.); 8,0 (detalhe sup.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_2);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-004', 'Perfil SU 004', 'OUTRO', 0.477, 'Código interno do fabricante: P-1251. Dimensões(raw): 71,0 (largura inf.); 30,0 (altura dir.); 17,0 (altura esq.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_2);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-005', 'Perfil SU 005', 'OUTRO', 1.008, 'Código interno do fabricante: P-1252. Dimensões(raw): 69,6 (largura inf.); 46,0 (altura dir.); 33,0 (altura esq.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_2);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-006', 'Perfil SU 006', 'OUTRO', 1.108, 'Código interno do fabricante: P-1253. Dimensões(raw): 69,6 (largura inf.); 60,0 (altura dir.); 33,0 (altura esq.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_2);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-007', 'Perfil SU 007', 'OUTRO', 0.372, 'Código interno do fabricante: P-1254. Dimensões(raw): 71,0 (largura sup.); 26,0 (altura dir.); 13,0 (altura esq.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_2);

INSERT INTO source_references (technical_source_id, page_number, extracted_by) VALUES (4, 3, 'agent-extraction');
SET @ref_4_3 = LAST_INSERT_ID();
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-008', 'Perfil SU 008', 'OUTRO', 0.238, 'Código interno do fabricante: P-1255. Dimensões(raw): 29,1 (largura); 15,7 (altura); 9,0 (detalhe sup.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_3);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-009', 'Perfil SU 009', 'OUTRO', 0.878, 'Código interno do fabricante: P-1256. Dimensões(raw): 51,5 (largura inf.); 69,6 (altura esq.); 26,0 (largura sup.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_3);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-010', 'Perfil SU 010', 'OUTRO', 1.008, 'Código interno do fabricante: P-1257. Dimensões(raw): 106,0 (largura sup.); 33,0 (altura esq.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_3);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-011', 'Perfil SU 011', 'OUTRO', 0.946, 'Código interno do fabricante: P-1258. Dimensões(raw): 106,0 (largura inf.); 47,0 (altura dir.); 33,0 (altura esq.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_3);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-012', 'Perfil SU 012', 'OUTRO', 0.547, 'Código interno do fabricante: P-1259. Dimensões(raw): 106,0 (largura sup.); 26,0 (altura dir.); 13,0 (altura esq.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_3);

INSERT INTO source_references (technical_source_id, page_number, extracted_by) VALUES (4, 4, 'agent-extraction');
SET @ref_4_4 = LAST_INSERT_ID();
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-023', 'Perfil SU 023', 'OUTRO', 0.808, 'Código interno do fabricante: P-1260. Dimensões(raw): 103,2 (largura inf.); 26,4 (altura dir.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_4);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-039', 'Perfil SU 039', 'OUTRO', 0.516, 'Código interno do fabricante: P-1261. Dimensões(raw): 25,0 (largura inf.); 52,6 (altura esq.); 41,6 (altura dir.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_4);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-040', 'Perfil SU 040', 'OUTRO', 0.478, 'Código interno do fabricante: P-1262. Dimensões(raw): 30,7 (largura inf.); 25,0 (largura sup.); 31,4 (altura esq.); 42,4 (altura dir.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_4);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-041', 'Perfil SU 041', 'OUTRO', 0.496, 'Código interno do fabricante: P-1263. Dimensões(raw): 33,0 (largura inf.); 25,0 (largura sup.); 31,4 (altura esq.); 42,4 (altura dir.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_4);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-047', 'Perfil SU 047', 'OUTRO', 1.003, 'Código interno do fabricante: P-1264. Dimensões(raw): 68,7 (largura sup./inf.); 42,4 (altura esq.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_4);

INSERT INTO source_references (technical_source_id, page_number, extracted_by) VALUES (4, 5, 'agent-extraction');
SET @ref_4_5 = LAST_INSERT_ID();
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-049', 'Perfil SU 049', 'OUTRO', 0.952, 'Código interno do fabricante: P-1265. Dimensões(raw): 71,0 (largura inf.); 39,2 (largura sup.); 31,4 (altura esq.); 42,4 (altura dir.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_5);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-053', 'Perfil SU 053', 'OUTRO', 0.474, 'Código interno do fabricante: P-1266. Dimensões(raw): 22,3 (largura inf.); 39,0 (altura esq.); 51,0 (altura dir.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_5);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-079', 'Perfil SU 079', 'OUTRO', 0.330, 'Código interno do fabricante: P-1267. Dimensões(raw): 25,0 (largura inf.); 28,7 (largura sup.); 35,0 (altura esq.); 20,0 (altura dir.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_5);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-080', 'Perfil SU 080', 'OUTRO', 0.329, 'Código interno do fabricante: P-1268. Dimensões(raw): 25,0 (largura inf.); 30,0 (altura esq.); 18,0 (altura dir.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_5);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-081', 'Perfil SU 081', 'OUTRO', 0.375, 'Código interno do fabricante: P-1269. Dimensões(raw): 26,3 (largura inf.); 25,0 (largura sup.); 42,8 (altura esq.); 18,0 (altura dir.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_5);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-082', 'Perfil SU 082', 'OUTRO', 0.362, 'Código interno do fabricante: P-1270. Dimensões(raw): 23,6 (largura inf.); 30,0 (altura esq.); 18,0 (altura dir.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_5);

INSERT INTO source_references (technical_source_id, page_number, extracted_by) VALUES (4, 6, 'agent-extraction');
SET @ref_4_6 = LAST_INSERT_ID();
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-276', 'Perfil SU 276', 'OUTRO', 0.174, 'Código interno do fabricante: P-1271. Dimensões(raw): 32,0 (largura sup.); 26,0 (altura dir.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_6);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-084', 'Perfil SU 084', 'OUTRO', 0.136, 'Código interno do fabricante: P-1272. Dimensões(raw): 26,2 (largura sup.); 12,8 e 15,5 (alturas dir., cotas segmentadas). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_6);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-085', 'Perfil SU 085', 'OUTRO', 0.486, 'Código interno do fabricante: P-1273. Dimensões(raw): 57,0 (largura sup.); 27,0 (largura inf.); 28,3 (altura esq.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_6);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-086', 'Perfil SU 086', 'OUTRO', 0.584, 'Código interno do fabricante: P-1274. Dimensões(raw): 57,0 (largura sup.); 27,0 (largura inf.); 28,3 (altura esq.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_6);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-102', 'Perfil SU 102', 'OUTRO', 0.119, 'Código interno do fabricante: P-1275. Dimensões(raw): 11,0 (largura sup.); 17,5 (largura inf.); 15,0 e 15,5 (alturas). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_6);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-103', 'Perfil SU 103', 'OUTRO', 0.148, 'Código interno do fabricante: P-1276. Dimensões(raw): 13,8 (largura sup.); 22,0 (largura inf.); 17,95 e 18,5 (alturas). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_6);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-111', 'Perfil SU 111', 'OUTRO', 0.604, 'Código interno do fabricante: P-1277. Dimensões(raw): 25,0 (largura inf.); 62,0 (altura esq.); 51,0 (altura dir.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_6);

INSERT INTO source_references (technical_source_id, page_number, extracted_by) VALUES (4, 7, 'agent-extraction');
SET @ref_4_7 = LAST_INSERT_ID();
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-225', 'Perfil SU 225', 'OUTRO', 0.933, 'Código interno do fabricante: P-1278. Dimensões(raw): 88,0 (largura sup.); 100,0 (largura inf.); 22,3 (altura dir.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_7);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-227', 'Perfil SU 227', 'OUTRO', 0.514, 'Código interno do fabricante: P-1279. Dimensões(raw): 33,0 (largura sup.); 57,0 (largura inf.); 22,2 (altura dir.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_7);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-228', 'Perfil SU 228', 'OUTRO', 0.602, 'Código interno do fabricante: P-1280. Dimensões(raw): 68,2 (largura inf.); 37,0 (altura dir.); 21,0 (altura esq.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_7);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-230', 'Perfil SU 230', 'OUTRO', 0.840, 'Código interno do fabricante: P-1281. Dimensões(raw): 103,2 (largura inf.); 37,0 (altura dir.); 21,0 (altura esq.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_7);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-242', 'Perfil SU 242', 'OUTRO', 0.657, 'Código interno do fabricante: P-1282. Dimensões(raw): 25,4 (largura sup.); 33,4 (largura inf.); 53,8 (altura esq.); 64,8 (altura dir.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_7);

INSERT INTO source_references (technical_source_id, page_number, extracted_by) VALUES (4, 8, 'agent-extraction');
SET @ref_4_8 = LAST_INSERT_ID();
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-243', 'Perfil SU 243', 'OUTRO', 0.624, 'Código interno do fabricante: P-1283. Dimensões(raw): 25,4 (largura sup.); 30,9 (largura inf.); 53,8 (altura esq.); 64,8 (altura dir.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_8);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-245', 'Perfil SU 245', 'OUTRO', 0.605, 'Código interno do fabricante: P-1284. Dimensões(raw): 25,4 (largura inf.); 53,8 (altura esq.); 64,8 (altura dir.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_8);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-250', 'Perfil SU 250', 'OUTRO', 0.720, 'Código interno do fabricante: P-1285. Dimensões(raw): 52,0 (largura sup.); 25,4 (largura inf.); 41,6 (altura esq.); 52,6 (altura dir.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_8);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-260', 'Perfil SU 260', 'OUTRO', 0.568, 'Código interno do fabricante: P-1286. Dimensões(raw): 68,2 (largura inf.); 23,0 (alturas esq./dir.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_8);

INSERT INTO source_references (technical_source_id, page_number, extracted_by) VALUES (4, 9, 'agent-extraction');
SET @ref_4_9 = LAST_INSERT_ID();
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-279', 'Perfil SU 279', 'OUTRO', 0.506, 'Código interno do fabricante: P-1287. Dimensões(raw): 33,3 (largura sup.); 26,5 (altura esq.); 41,3 (altura dir.). Aplicação: não encontrado. Condição comercial junto a este perfil na fonte: "Pedido mínimo: 300 kg / Barras de 6 metros" (aplicabilidade a todos os perfis ou só a este não está clara no documento).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_9);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, weight_kg_per_m, description, origin_type, status_code, source_reference_id) VALUES (3, 6, 'SU-280', 'Perfil SU 280', 'OUTRO', 0.890, 'Código interno do fabricante: P-1288. Dimensões(raw): 55,2 (largura sup.); 25,4 (largura inf.); 64,8 (altura dir.). Aplicação: não encontrado.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @ref_4_9);
