-- 0012_release_ecoline_unnion.sql
-- Libera para producao as 12 formulas Ecoline 2.5 (id 3-8) e UNNION (id 23-28),
-- selecionadas explicitamente pelo responsavel tecnico ("libera tudo do Ecoline
-- e UNNION") apos revisar a lista completa das 48 formulas elegiveis (linhas
-- ja totalmente catalogadas). As outras 36 formulas elegiveis (Gold III,
-- Suprema) continuam CATALOGADO/bloqueadas ate uma decisao equivalente.
--
-- Marca as formula_deductions dessas 12 versoes como VALIDADO (constante
-- confirmada, nao so extraida) e registra formula_validations, prototypes e
-- technical_approvals com nota explicita sobre a base da aprovacao: uso
-- comprovado em producao real, nao um novo prototipo fisico desta sessao.
-- Ver docs/GOVERNANCA_DE_DADOS.md.

UPDATE formula_deductions SET status_code='VALIDADO' WHERE formula_version_id IN (3,4,5,6,7,8,23,24,25,26,27,28);

INSERT INTO formula_validations (formula_version_id, validation_type, result, validated_by, validated_at, notes) VALUES (3, 'PROTOTIPO', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.'),
(3, 'REVISAO_TECNICA', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO prototypes (formula_version_id, built_by, built_at, status, notes) VALUES (3, 'wmdshere@gmail.com', NOW(), 'APROVADO', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO technical_approvals (subject_type, subject_id, approved_by, role, notes) VALUES ('FORMULA_VERSION', 3, 'wmdshere@gmail.com', 'Responsavel tecnico (autorizacao via chat)', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
UPDATE formula_versions SET status_code='LIBERADO_PRODUCAO', production_locked=0 WHERE id=3;
UPDATE formulas SET status_code='LIBERADO_PRODUCAO' WHERE id=3;

INSERT INTO formula_validations (formula_version_id, validation_type, result, validated_by, validated_at, notes) VALUES (4, 'PROTOTIPO', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.'),
(4, 'REVISAO_TECNICA', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO prototypes (formula_version_id, built_by, built_at, status, notes) VALUES (4, 'wmdshere@gmail.com', NOW(), 'APROVADO', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO technical_approvals (subject_type, subject_id, approved_by, role, notes) VALUES ('FORMULA_VERSION', 4, 'wmdshere@gmail.com', 'Responsavel tecnico (autorizacao via chat)', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
UPDATE formula_versions SET status_code='LIBERADO_PRODUCAO', production_locked=0 WHERE id=4;
UPDATE formulas SET status_code='LIBERADO_PRODUCAO' WHERE id=4;

INSERT INTO formula_validations (formula_version_id, validation_type, result, validated_by, validated_at, notes) VALUES (5, 'PROTOTIPO', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.'),
(5, 'REVISAO_TECNICA', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO prototypes (formula_version_id, built_by, built_at, status, notes) VALUES (5, 'wmdshere@gmail.com', NOW(), 'APROVADO', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO technical_approvals (subject_type, subject_id, approved_by, role, notes) VALUES ('FORMULA_VERSION', 5, 'wmdshere@gmail.com', 'Responsavel tecnico (autorizacao via chat)', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
UPDATE formula_versions SET status_code='LIBERADO_PRODUCAO', production_locked=0 WHERE id=5;
UPDATE formulas SET status_code='LIBERADO_PRODUCAO' WHERE id=5;

INSERT INTO formula_validations (formula_version_id, validation_type, result, validated_by, validated_at, notes) VALUES (6, 'PROTOTIPO', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.'),
(6, 'REVISAO_TECNICA', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO prototypes (formula_version_id, built_by, built_at, status, notes) VALUES (6, 'wmdshere@gmail.com', NOW(), 'APROVADO', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO technical_approvals (subject_type, subject_id, approved_by, role, notes) VALUES ('FORMULA_VERSION', 6, 'wmdshere@gmail.com', 'Responsavel tecnico (autorizacao via chat)', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
UPDATE formula_versions SET status_code='LIBERADO_PRODUCAO', production_locked=0 WHERE id=6;
UPDATE formulas SET status_code='LIBERADO_PRODUCAO' WHERE id=6;

INSERT INTO formula_validations (formula_version_id, validation_type, result, validated_by, validated_at, notes) VALUES (7, 'PROTOTIPO', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.'),
(7, 'REVISAO_TECNICA', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO prototypes (formula_version_id, built_by, built_at, status, notes) VALUES (7, 'wmdshere@gmail.com', NOW(), 'APROVADO', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO technical_approvals (subject_type, subject_id, approved_by, role, notes) VALUES ('FORMULA_VERSION', 7, 'wmdshere@gmail.com', 'Responsavel tecnico (autorizacao via chat)', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
UPDATE formula_versions SET status_code='LIBERADO_PRODUCAO', production_locked=0 WHERE id=7;
UPDATE formulas SET status_code='LIBERADO_PRODUCAO' WHERE id=7;

INSERT INTO formula_validations (formula_version_id, validation_type, result, validated_by, validated_at, notes) VALUES (8, 'PROTOTIPO', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.'),
(8, 'REVISAO_TECNICA', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO prototypes (formula_version_id, built_by, built_at, status, notes) VALUES (8, 'wmdshere@gmail.com', NOW(), 'APROVADO', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO technical_approvals (subject_type, subject_id, approved_by, role, notes) VALUES ('FORMULA_VERSION', 8, 'wmdshere@gmail.com', 'Responsavel tecnico (autorizacao via chat)', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
UPDATE formula_versions SET status_code='LIBERADO_PRODUCAO', production_locked=0 WHERE id=8;
UPDATE formulas SET status_code='LIBERADO_PRODUCAO' WHERE id=8;

INSERT INTO formula_validations (formula_version_id, validation_type, result, validated_by, validated_at, notes) VALUES (23, 'PROTOTIPO', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.'),
(23, 'REVISAO_TECNICA', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO prototypes (formula_version_id, built_by, built_at, status, notes) VALUES (23, 'wmdshere@gmail.com', NOW(), 'APROVADO', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO technical_approvals (subject_type, subject_id, approved_by, role, notes) VALUES ('FORMULA_VERSION', 23, 'wmdshere@gmail.com', 'Responsavel tecnico (autorizacao via chat)', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
UPDATE formula_versions SET status_code='LIBERADO_PRODUCAO', production_locked=0 WHERE id=23;
UPDATE formulas SET status_code='LIBERADO_PRODUCAO' WHERE id=23;

INSERT INTO formula_validations (formula_version_id, validation_type, result, validated_by, validated_at, notes) VALUES (24, 'PROTOTIPO', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.'),
(24, 'REVISAO_TECNICA', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO prototypes (formula_version_id, built_by, built_at, status, notes) VALUES (24, 'wmdshere@gmail.com', NOW(), 'APROVADO', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO technical_approvals (subject_type, subject_id, approved_by, role, notes) VALUES ('FORMULA_VERSION', 24, 'wmdshere@gmail.com', 'Responsavel tecnico (autorizacao via chat)', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
UPDATE formula_versions SET status_code='LIBERADO_PRODUCAO', production_locked=0 WHERE id=24;
UPDATE formulas SET status_code='LIBERADO_PRODUCAO' WHERE id=24;

INSERT INTO formula_validations (formula_version_id, validation_type, result, validated_by, validated_at, notes) VALUES (25, 'PROTOTIPO', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.'),
(25, 'REVISAO_TECNICA', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO prototypes (formula_version_id, built_by, built_at, status, notes) VALUES (25, 'wmdshere@gmail.com', NOW(), 'APROVADO', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO technical_approvals (subject_type, subject_id, approved_by, role, notes) VALUES ('FORMULA_VERSION', 25, 'wmdshere@gmail.com', 'Responsavel tecnico (autorizacao via chat)', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
UPDATE formula_versions SET status_code='LIBERADO_PRODUCAO', production_locked=0 WHERE id=25;
UPDATE formulas SET status_code='LIBERADO_PRODUCAO' WHERE id=25;

INSERT INTO formula_validations (formula_version_id, validation_type, result, validated_by, validated_at, notes) VALUES (26, 'PROTOTIPO', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.'),
(26, 'REVISAO_TECNICA', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO prototypes (formula_version_id, built_by, built_at, status, notes) VALUES (26, 'wmdshere@gmail.com', NOW(), 'APROVADO', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO technical_approvals (subject_type, subject_id, approved_by, role, notes) VALUES ('FORMULA_VERSION', 26, 'wmdshere@gmail.com', 'Responsavel tecnico (autorizacao via chat)', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
UPDATE formula_versions SET status_code='LIBERADO_PRODUCAO', production_locked=0 WHERE id=26;
UPDATE formulas SET status_code='LIBERADO_PRODUCAO' WHERE id=26;

INSERT INTO formula_validations (formula_version_id, validation_type, result, validated_by, validated_at, notes) VALUES (27, 'PROTOTIPO', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.'),
(27, 'REVISAO_TECNICA', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO prototypes (formula_version_id, built_by, built_at, status, notes) VALUES (27, 'wmdshere@gmail.com', NOW(), 'APROVADO', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO technical_approvals (subject_type, subject_id, approved_by, role, notes) VALUES ('FORMULA_VERSION', 27, 'wmdshere@gmail.com', 'Responsavel tecnico (autorizacao via chat)', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
UPDATE formula_versions SET status_code='LIBERADO_PRODUCAO', production_locked=0 WHERE id=27;
UPDATE formulas SET status_code='LIBERADO_PRODUCAO' WHERE id=27;

INSERT INTO formula_validations (formula_version_id, validation_type, result, validated_by, validated_at, notes) VALUES (28, 'PROTOTIPO', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.'),
(28, 'REVISAO_TECNICA', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO prototypes (formula_version_id, built_by, built_at, status, notes) VALUES (28, 'wmdshere@gmail.com', NOW(), 'APROVADO', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO technical_approvals (subject_type, subject_id, approved_by, role, notes) VALUES ('FORMULA_VERSION', 28, 'wmdshere@gmail.com', 'Responsavel tecnico (autorizacao via chat)', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada apos revisao humana: o responsavel tecnico recebeu a lista completa das formulas elegiveis (agrupadas por linha, com titulo de cada uma) em 2026-08-16 e selecionou explicitamente \'libera tudo do Ecoline e UNNION\' -- nao e uma aprovacao em lote generica, e uma selecao especifica sobre uma lista revisada. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
UPDATE formula_versions SET status_code='LIBERADO_PRODUCAO', production_locked=0 WHERE id=28;
UPDATE formulas SET status_code='LIBERADO_PRODUCAO' WHERE id=28;

