-- 0015_alcoa_suprema_portao_moveleira.sql
-- Decisao explicita do responsavel tecnico (2026-08-16): usar o indice de perfis do
-- Catalogo Alcoa (fonte 11, ja carregada em 0014) como base para (a) resolver o conflito
-- de peso da linha Suprema e (b) tentar confirmar o fabricante de Linha Portao e Linha
-- Moveleira, que seguiam NECESSITA_CONFERENCIA.
--
-- IMPORTANTE sobre forca de evidencia (nao e a mesma para as 3 linhas):
--  * Suprema: 36 de 41 codigos (88%) batem, todos na faixa de pagina 157-202
--    (secao 'Linha Suprema' do indice Alcoa), diferenca de peso pequena e sistematica
--    (+1% a +11%, quase sempre Alcoa > TEC-SUP) -- evidencia forte de que e o mesmo perfil.
--  * Linha Moveleira: 6 de 12 codigos verificados (50%) batem, mas em
--    paginas espalhadas (54, 69, 174-188) em vez de uma secao unica -- consistente com pecas
--    genericas (baguete, remate) reaproveitadas em varias linhas do catalogo, evidencia mais
--    fraca que a de Suprema/Modulo Pratico.
--  * Linha Portao: 2 de 8 codigos (25%) batem -- no limite minimo do
--    criterio (n>=2, ratio>=0.25), e um dos dois (PU-639) aparece com pagina divergente em
--    outro ponto do proprio indice Alcoa (conflito interno da fonte). Confirmacao mais fraca
--    das tres; recomenda-se conferencia com o fabricante antes de tratar como definitiva.

INSERT INTO source_references (technical_source_id, section_title, excerpt, extracted_by) VALUES
(11, 'Indice de Perfis (Catalogo Alcoa) - secao Linha Suprema (pag. 157-202)',
'Codigos da linha Suprema ja cadastrados (fonte TEC-SUP) que tambem aparecem no indice Alcoa, usados para resolver o conflito de peso por decisao do responsavel tecnico: SU-001 0.762 pag.157 (TEC-SUP: 0.714); SU-002 0.707 pag.157 (TEC-SUP: 0.643); SU-003 0.523 pag.157 (TEC-SUP: 0.469); SU-004 0.504 pag.158 (TEC-SUP: 0.477); SU-005 1.108 pag.158 (TEC-SUP: 1.008); SU-006 1.086 pag.158 (TEC-SUP: 1.108); SU-007 0.382 pag.159 (TEC-SUP: 0.372); SU-008 0.244 pag.159 (TEC-SUP: 0.238); SU-009 0.908 pag.159 (TEC-SUP: 0.878); SU-010 1.022 pag.160 (TEC-SUP: 1.008); SU-011 0.981 pag.160 (TEC-SUP: 0.946); SU-012 0.539 pag.160 (TEC-SUP: 0.547); SU-039 0.520 pag.171 (TEC-SUP: 0.516); SU-040 0.480 pag.171 (TEC-SUP: 0.478); SU-041 0.507 pag.171 (TEC-SUP: 0.496); SU-047 1.041 pag.173 (TEC-SUP: 1.003); SU-049 1.052 pag.173 (TEC-SUP: 0.952); SU-053 0.507 pag.174 (TEC-SUP: 0.474); SU-079 0.341 pag.182 (TEC-SUP: 0.33); SU-080 0.360 pag.181 (TEC-SUP: 0.329); SU-081 0.412 pag.181 (TEC-SUP: 0.375); SU-082 0.382 pag.181 (TEC-SUP: 0.362); SU-084 0.125 pag.181 (TEC-SUP: 0.136); SU-085 0.501 pag.182 (TEC-SUP: 0.486); SU-086 0.596 pag.182 (TEC-SUP: 0.584); SU-102 0.111 pag.185 (TEC-SUP: 0.119); SU-103 0.140 pag.185 (TEC-SUP: 0.148); SU-111 0.640 pag.188 (TEC-SUP: 0.604); SU-225 0.989 pag.174 (TEC-SUP: 0.933); SU-227 0.550 pag.174 (TEC-SUP: 0.514); SU-228 0.688 pag.162 (TEC-SUP: 0.602); SU-230 0.954 pag.162 (TEC-SUP: 0.84); SU-250 0.736 pag.172 (TEC-SUP: 0.72); SU-260 0.631 pag.163 (TEC-SUP: 0.568); SU-279 0.565 pag.186 (TEC-SUP: 0.506); SU-280 1.006 pag.169 (TEC-SUP: 0.89)',
'analise-catalogo-consolidado');
SET @ref_suprema = LAST_INSERT_ID();

INSERT INTO source_references (technical_source_id, section_title, excerpt, extracted_by) VALUES
(11, 'Indice de Perfis (Catalogo Alcoa) - amostra usada para Linha Portao',
'PU-639 0.390 pag.2; LB-050 0.624 pag.72. Evidencia fraca (2 de 8 codigos da linha, no limite minimo do criterio de classificacao, com conflito de pagina para PU-639 em outro ponto do mesmo indice).',
'analise-catalogo-consolidado');
SET @ref_portao = LAST_INSERT_ID();

INSERT INTO source_references (technical_source_id, section_title, excerpt, extracted_by) VALUES
(11, 'Indice de Perfis (Catalogo Alcoa) - amostra usada para Linha Moveleira',
'BG-010 0.115 pag.54; SU-050 0.921 pag.174; SU-102 0.111 pag.185; SU-111 0.640 pag.188; SU-279 0.565 pag.186; US-294 0.268 pag.69. Codigos batidos em paginas espalhadas do indice, nao uma secao unica -- evidencia de fabricante, nao necessariamente de peso especifico para uso em producao.',
'analise-catalogo-consolidado');
SET @ref_moveleira = LAST_INSERT_ID();

-- === SUPREMA (product_line_id=6): reclassificada para Alcoa; peso atualizado para os
-- === codigos com correspondencia no indice Alcoa, preservando o valor TEC-SUP anterior no
-- === historico da descricao (nunca apagado, so superado por decisao humana explicita).
UPDATE product_lines SET
manufacturer_id = 2,
status_code = 'CATALOGADO',
description = CONCAT(description, ' | Reclassificada como Alcoa em 2026-08-16 por decisao explicita do responsavel tecnico: 36 de 41 codigos (88%) da linha batem codigo+peso+pagina com a secao "Linha Suprema" do indice de perfis Alcoa (pags. 157-202); a divergencia de peso entre TEC-SUP e Alcoa (antes um conflito nao resolvido) foi resolvida adotando os valores do catalogo Alcoa. Ver source_references.id=', @ref_suprema, '.'),
source_reference_id = @ref_suprema
WHERE id = 6;

UPDATE profiles SET manufacturer_id = 2 WHERE product_line_id = 6;

UPDATE profiles SET weight_kg_per_m=0.762, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.762 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 157) em 2026-08-16, substituindo o valor anterior 0.714 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-001';
UPDATE profiles SET weight_kg_per_m=0.707, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.707 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 157) em 2026-08-16, substituindo o valor anterior 0.643 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-002';
UPDATE profiles SET weight_kg_per_m=0.523, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.523 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 157) em 2026-08-16, substituindo o valor anterior 0.469 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-003';
UPDATE profiles SET weight_kg_per_m=0.504, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.504 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 158) em 2026-08-16, substituindo o valor anterior 0.477 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-004';
UPDATE profiles SET weight_kg_per_m=1.108, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 1.108 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 158) em 2026-08-16, substituindo o valor anterior 1.008 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-005';
UPDATE profiles SET weight_kg_per_m=1.086, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 1.086 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 158) em 2026-08-16, substituindo o valor anterior 1.108 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-006';
UPDATE profiles SET weight_kg_per_m=0.382, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.382 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 159) em 2026-08-16, substituindo o valor anterior 0.372 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-007';
UPDATE profiles SET weight_kg_per_m=0.244, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.244 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 159) em 2026-08-16, substituindo o valor anterior 0.238 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-008';
UPDATE profiles SET weight_kg_per_m=0.908, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.908 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 159) em 2026-08-16, substituindo o valor anterior 0.878 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-009';
UPDATE profiles SET weight_kg_per_m=1.022, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 1.022 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 160) em 2026-08-16, substituindo o valor anterior 1.008 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-010';
UPDATE profiles SET weight_kg_per_m=0.981, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.981 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 160) em 2026-08-16, substituindo o valor anterior 0.946 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-011';
UPDATE profiles SET weight_kg_per_m=0.539, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.539 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 160) em 2026-08-16, substituindo o valor anterior 0.547 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-012';
UPDATE profiles SET weight_kg_per_m=0.520, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.520 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 171) em 2026-08-16, substituindo o valor anterior 0.516 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-039';
UPDATE profiles SET weight_kg_per_m=0.480, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.480 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 171) em 2026-08-16, substituindo o valor anterior 0.478 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-040';
UPDATE profiles SET weight_kg_per_m=0.507, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.507 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 171) em 2026-08-16, substituindo o valor anterior 0.496 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-041';
UPDATE profiles SET weight_kg_per_m=1.041, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 1.041 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 173) em 2026-08-16, substituindo o valor anterior 1.003 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-047';
UPDATE profiles SET weight_kg_per_m=1.052, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 1.052 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 173) em 2026-08-16, substituindo o valor anterior 0.952 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-049';
UPDATE profiles SET weight_kg_per_m=0.507, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.507 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 174) em 2026-08-16, substituindo o valor anterior 0.474 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-053';
UPDATE profiles SET weight_kg_per_m=0.341, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.341 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 182) em 2026-08-16, substituindo o valor anterior 0.33 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-079';
UPDATE profiles SET weight_kg_per_m=0.360, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.360 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 181) em 2026-08-16, substituindo o valor anterior 0.329 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-080';
UPDATE profiles SET weight_kg_per_m=0.412, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.412 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 181) em 2026-08-16, substituindo o valor anterior 0.375 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-081';
UPDATE profiles SET weight_kg_per_m=0.382, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.382 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 181) em 2026-08-16, substituindo o valor anterior 0.362 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-082';
UPDATE profiles SET weight_kg_per_m=0.125, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.125 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 181) em 2026-08-16, substituindo o valor anterior 0.136 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-084';
UPDATE profiles SET weight_kg_per_m=0.501, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.501 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 182) em 2026-08-16, substituindo o valor anterior 0.486 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-085';
UPDATE profiles SET weight_kg_per_m=0.596, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.596 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 182) em 2026-08-16, substituindo o valor anterior 0.584 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-086';
UPDATE profiles SET weight_kg_per_m=0.111, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.111 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 185) em 2026-08-16, substituindo o valor anterior 0.119 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-102';
UPDATE profiles SET weight_kg_per_m=0.140, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.140 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 185) em 2026-08-16, substituindo o valor anterior 0.148 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-103';
UPDATE profiles SET weight_kg_per_m=0.640, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.640 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 188) em 2026-08-16, substituindo o valor anterior 0.604 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-111';
UPDATE profiles SET weight_kg_per_m=0.989, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.989 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 174) em 2026-08-16, substituindo o valor anterior 0.933 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-225';
UPDATE profiles SET weight_kg_per_m=0.550, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.550 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 174) em 2026-08-16, substituindo o valor anterior 0.514 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-227';
UPDATE profiles SET weight_kg_per_m=0.688, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.688 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 162) em 2026-08-16, substituindo o valor anterior 0.602 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-228';
UPDATE profiles SET weight_kg_per_m=0.954, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.954 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 162) em 2026-08-16, substituindo o valor anterior 0.84 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-230';
UPDATE profiles SET weight_kg_per_m=0.736, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.736 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 172) em 2026-08-16, substituindo o valor anterior 0.72 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-250';
UPDATE profiles SET weight_kg_per_m=0.631, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.631 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 163) em 2026-08-16, substituindo o valor anterior 0.568 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-260';
UPDATE profiles SET weight_kg_per_m=0.565, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 0.565 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 186) em 2026-08-16, substituindo o valor anterior 0.506 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-279';
UPDATE profiles SET weight_kg_per_m=1.006, origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_suprema, description=CONCAT(description, ' | Peso atualizado para 1.006 kg/m (Catalogo Alcoa, Indice de Perfis, pag. 169) em 2026-08-16, substituindo o valor anterior 0.89 kg/m do catalogo TEC-SUP por decisao do responsavel tecnico -- ver docs/GOVERNANCA_DE_DADOS.md.') WHERE product_line_id=6 AND code='SU-280';

-- === LINHA PORTAO (product_line_id=8): evidencia fraca (ver nota acima), aplicada por
-- === instrucao explicita do usuario. Fica CATALOGADO, nao VALIDADO -- recomenda-se conferir
-- === com o fabricante antes de tratar como definitivo.
UPDATE product_lines SET
manufacturer_id = 2,
status_code = 'CATALOGADO',
description = CONCAT(description, ' | Fabricante atribuido a Alcoa em 2026-08-16 por instrucao explicita do usuario, com evidencia FRACA: apenas 2 de 8 codigos distintos da linha (PU-639, LB-050) batem contra o indice de perfis Alcoa, no limite minimo do criterio de classificacao, e PU-639 aparece com pagina divergente em outro ponto do mesmo indice (conflito interno da fonte). Recomenda-se confirmar com o fabricante antes de tratar como definitivo. Ver source_references.id=', @ref_portao, '.'),
source_reference_id = @ref_portao
WHERE id = 8;

UPDATE profiles SET manufacturer_id = 2 WHERE product_line_id = 8;

UPDATE profiles SET weight_kg_per_m=0.390, status_code='CATALOGADO', origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_portao, description=CONCAT(COALESCE(description,''), ' | Peso: Catalogo Alcoa, Indice de Perfis, pag. 2 (evidencia fraca, ver nota da linha).') WHERE product_line_id=8 AND code='PU-639';
UPDATE profiles SET weight_kg_per_m=0.624, status_code='CATALOGADO', origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_portao, description=CONCAT(COALESCE(description,''), ' | Peso: Catalogo Alcoa, Indice de Perfis, pag. 72 (evidencia fraca, ver nota da linha).') WHERE product_line_id=8 AND code='LB-050';

-- === LINHA MOVELEIRA (product_line_id=9): tinha atribuicao fraca anterior (so mencao na
-- === contracapa do catalogo Ecoline 2.5, sem codigo). Evidencia de codigo contra o indice
-- === Alcoa (50%, paginas espalhadas) e mais forte que a mencao anterior, entao substitui.
UPDATE product_lines SET
manufacturer_id = 2,
status_code = 'CATALOGADO',
description = CONCAT(description, ' | Fabricante reatribuido a Alcoa em 2026-08-16 por instrucao explicita do usuario: 6 de 12 codigos verificados (50%) batem contra o indice de perfis Alcoa, superando a evidencia anterior (mera mencao textual na contracapa do catalogo Ecoline 2.5, sem codigo). Paginas espalhadas (nao uma secao unica), entao a confianca no fabricante e maior que no peso individual de cada perfil. Ver source_references.id=', @ref_moveleira, '.'),
source_reference_id = @ref_moveleira
WHERE id = 9;

UPDATE profiles SET manufacturer_id = 2 WHERE product_line_id = 9;

UPDATE profiles SET weight_kg_per_m=0.115, status_code='CATALOGADO', origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_moveleira, description=CONCAT(COALESCE(description,''), ' | Peso: Catalogo Alcoa, Indice de Perfis, pag. 54.') WHERE product_line_id=9 AND code='BG-010';
UPDATE profiles SET weight_kg_per_m=0.921, status_code='CATALOGADO', origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_moveleira, description=CONCAT(COALESCE(description,''), ' | Peso: Catalogo Alcoa, Indice de Perfis, pag. 174.') WHERE product_line_id=9 AND code='SU-050';
UPDATE profiles SET weight_kg_per_m=0.111, status_code='CATALOGADO', origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_moveleira, description=CONCAT(COALESCE(description,''), ' | Peso: Catalogo Alcoa, Indice de Perfis, pag. 185.') WHERE product_line_id=9 AND code='SU-102';
UPDATE profiles SET weight_kg_per_m=0.640, status_code='CATALOGADO', origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_moveleira, description=CONCAT(COALESCE(description,''), ' | Peso: Catalogo Alcoa, Indice de Perfis, pag. 188.') WHERE product_line_id=9 AND code='SU-111';
UPDATE profiles SET weight_kg_per_m=0.565, status_code='CATALOGADO', origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_moveleira, description=CONCAT(COALESCE(description,''), ' | Peso: Catalogo Alcoa, Indice de Perfis, pag. 186.') WHERE product_line_id=9 AND code='SU-279';
UPDATE profiles SET weight_kg_per_m=0.268, status_code='CATALOGADO', origin_type='ENCONTRADO_DOCUMENTO', source_reference_id=@ref_moveleira, description=CONCAT(COALESCE(description,''), ' | Peso: Catalogo Alcoa, Indice de Perfis, pag. 69.') WHERE product_line_id=9 AND code='US-294';
