-- 0016_al_industria.sql
-- Novo catalogo enviado pelo usuario (CatalogoAL.pdf, 44 paginas). IMPORTANTE: este arquivo
-- e o catalogo da 'AL Industria' (Rua Juraci Aletto 224, Maua-SP, tel (11) 2137-7300,
-- alindustria.com.br), fabricante de FERRAGENS para vidro temperado (dobradicas, fechaduras,
-- puxadores, suportes) e de kits de aluminio (Kit Sacada, Kit Pia, Kit Box, Kit Engenharia) --
-- NAO e o Catalogo Alcoa (fabricante de perfil de esquadria) usado em 0014/0015. O nome do
-- arquivo ('CatalogoAL') e o nome do fabricante ('Alcoa') parecem ter sido confundidos no
-- pedido do usuario; os dados abaixo sao creditados ao fabricante correto conforme a propria
-- capa/rodape do documento, para nao inventar uma fonte que o documento nao e.
--
-- Cobertura: ferragens para porta/janela de vidro (Linha Capa e Linha Tradicional, mesmo
-- desenho tecnico, cores diferentes -- creditadas como pares no mesmo registro), puxadores
-- (polimero/inox/aluminio/aco carbono, dimensoes reais tabuladas), e as pecas de secao dos
-- kits de aluminio com os descontos (folgas) citados literalmente no catalogo.

INSERT INTO manufacturers (id, name, legal_name, website, notes) VALUES
(8, 'AL Industria', NULL, 'alindustria.com.br', 'Ferragens para vidro temperado (dobradicas, fechaduras, puxadores, suportes) e kits de aluminio (Kit Sacada, Kit Pia, Kit Box, Kit Engenharia). Endereco: Rua Juraci Aletto, 224 - Galpao B, Sertaozinho, Maua-SP, CEP 09370-813. Tel: +55 (11) 2137-7300. Fundada em 2003 por Max Le Leuxhe; primeira empresa a injetar ferragens em polimero, segundo o proprio catalogo.');

INSERT INTO technical_sources (id, manufacturer_id, title, file_name, source_url, edition, document_type, is_uploaded, page_count, notes) VALUES
(12, 8, 'Catalogo AL Industria', '9a734993-CatalogoAL.pdf', 'alindustria.com.br', 'Junho/2022', 'CATALOGO', 1, 44,
'Catalogo comercial da AL Industria: Linha Capa e Linha Tradicional de ferragens para vidro (mesmo desenho tecnico, cores diferentes), puxadores (polimero/inox/aluminio/aco), e kits de aluminio extrudado (Kit Sacada sem Rolamento, Kit Pia 6/8mm, Kit Box 8mm, Kit Box Reto 8mm, Kit Engenharia 8mm/10mm) com folgas/descontos de vao citados no proprio catalogo.');

INSERT INTO source_references (technical_source_id, page_number, section_title, excerpt, extracted_by) VALUES
(12, 16, 'Catalogo AL Industria - pagina 16', 'Codigos e dimensoes (mm) extraidos diretamente da pagina 16 do catalogo.', 'analise-catalogo-al-industria'),
(12, 17, 'Catalogo AL Industria - pagina 17', 'Codigos e dimensoes (mm) extraidos diretamente da pagina 17 do catalogo.', 'analise-catalogo-al-industria'),
(12, 18, 'Catalogo AL Industria - pagina 18', 'Codigos e dimensoes (mm) extraidos diretamente da pagina 18 do catalogo.', 'analise-catalogo-al-industria'),
(12, 19, 'Catalogo AL Industria - pagina 19', 'Codigos e dimensoes (mm) extraidos diretamente da pagina 19 do catalogo.', 'analise-catalogo-al-industria'),
(12, 20, 'Catalogo AL Industria - pagina 20', 'Codigos e dimensoes (mm) extraidos diretamente da pagina 20 do catalogo.', 'analise-catalogo-al-industria'),
(12, 21, 'Catalogo AL Industria - pagina 21', 'Codigos e dimensoes (mm) extraidos diretamente da pagina 21 do catalogo.', 'analise-catalogo-al-industria'),
(12, 22, 'Catalogo AL Industria - pagina 22', 'Codigos e dimensoes (mm) extraidos diretamente da pagina 22 do catalogo.', 'analise-catalogo-al-industria'),
(12, 23, 'Catalogo AL Industria - pagina 23', 'Codigos e dimensoes (mm) extraidos diretamente da pagina 23 do catalogo.', 'analise-catalogo-al-industria'),
(12, 24, 'Catalogo AL Industria - pagina 24', 'Codigos e dimensoes (mm) extraidos diretamente da pagina 24 do catalogo.', 'analise-catalogo-al-industria'),
(12, 25, 'Catalogo AL Industria - pagina 25', 'Codigos e dimensoes (mm) extraidos diretamente da pagina 25 do catalogo.', 'analise-catalogo-al-industria'),
(12, 26, 'Catalogo AL Industria - pagina 26', 'Codigos e dimensoes (mm) extraidos diretamente da pagina 26 do catalogo.', 'analise-catalogo-al-industria'),
(12, 27, 'Catalogo AL Industria - pagina 27', 'Codigos e dimensoes (mm) extraidos diretamente da pagina 27 do catalogo.', 'analise-catalogo-al-industria'),
(12, 28, 'Catalogo AL Industria - pagina 28', 'Codigos e dimensoes (mm) extraidos diretamente da pagina 28 do catalogo.', 'analise-catalogo-al-industria'),
(12, 29, 'Catalogo AL Industria - pagina 29', 'Codigos e dimensoes (mm) extraidos diretamente da pagina 29 do catalogo.', 'analise-catalogo-al-industria'),
(12, 30, 'Catalogo AL Industria - pagina 30', 'Codigos e dimensoes (mm) extraidos diretamente da pagina 30 do catalogo.', 'analise-catalogo-al-industria'),
(12, 31, 'Catalogo AL Industria - pagina 31', 'Codigos e dimensoes (mm) extraidos diretamente da pagina 31 do catalogo.', 'analise-catalogo-al-industria'),
(12, 32, 'Catalogo AL Industria - pagina 32', 'Codigos e dimensoes (mm) extraidos diretamente da pagina 32 do catalogo.', 'analise-catalogo-al-industria'),
(12, 33, 'Catalogo AL Industria - pagina 33', 'Codigos e dimensoes (mm) extraidos diretamente da pagina 33 do catalogo.', 'analise-catalogo-al-industria'),
(12, 39, 'Catalogo AL Industria - pagina 39', 'Codigos e dimensoes (mm) extraidos diretamente da pagina 39 do catalogo.', 'analise-catalogo-al-industria'),
(12, 40, 'Catalogo AL Industria - pagina 40', 'Codigos e dimensoes (mm) extraidos diretamente da pagina 40 do catalogo.', 'analise-catalogo-al-industria'),
(12, 41, 'Catalogo AL Industria - pagina 41', 'Codigos e dimensoes (mm) extraidos diretamente da pagina 41 do catalogo.', 'analise-catalogo-al-industria');
SET @al_first_ref = LAST_INSERT_ID();
-- source_references acima foram inseridos em sequencia para as paginas: [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 39, 40, 41]
-- (assume-se que o MySQL/MariaDB atribui IDs consecutivos dentro do mesmo INSERT multi-linha;
-- calculamos o id de cada pagina por offset a partir de @al_first_ref)

-- === Ferragens (Linha Capa / Linha Tradicional) ===
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1001', 'Botão de correção com calota para vidro', 'OUTRO', '7x11x18mm; par de linha: CAPA-1001. Fonte: Catalogo AL Industria, pag. 16.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_first_ref);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1002', 'Botão de correção simples (parafuso)', 'OUTRO', '22x8mm; par: CAPA-1002. Fonte: Catalogo AL Industria, pag. 16.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_first_ref);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1002A', 'Botão de correção (lâmina)', 'OUTRO', '23x16x12mm; par: CAPA-1002A. Fonte: Catalogo AL Industria, pag. 16.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_first_ref);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1002B', 'Botão de correção (lâmina com calota)', 'OUTRO', '18x18x10mm; par: CAPA-1002B. Fonte: Catalogo AL Industria, pag. 16.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_first_ref);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1003A', 'Argolas para corrente', 'OUTRO', '27mm; par: CAPA-1003A. Fonte: Catalogo AL Industria, pag. 16.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_first_ref);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1003F', 'Corrente para trinco basculante, por metro', 'OUTRO', '1000mm; par: CAPA-1003F. Fonte: Catalogo AL Industria, pag. 17.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 1));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1005', 'Calota para corrente', 'OUTRO', '19x11mm; par: CAPA-1005. Fonte: Catalogo AL Industria, pag. 17.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 1));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1005A', 'Calota para nylon com regulagem', 'OUTRO', 'par: CAPA-1005A. Fonte: Catalogo AL Industria, pag. 17.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 1));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1013', 'Pivô para dobradiça inferior com regulagem', 'OUTRO', '60x31x16mm; par: CAPA-1013. Fonte: Catalogo AL Industria, pag. 17.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 1));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1013A', 'Pivô para dobradiça com pino fixo', 'OUTRO', '25x62x9mm; par: CAPA-1013A. Fonte: Catalogo AL Industria, pag. 17.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 1));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1013F', 'Pino para dobradiça inferior AL-1103A', 'OUTRO', '67x22mm; par: CAPA-1013F. Fonte: Catalogo AL Industria, pag. 18.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 2));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1038', 'Capuchinho para trinco com furo de 10mm', 'OUTRO', '19x23x13/10mm; par: CAPA-1038. Fonte: Catalogo AL Industria, pag. 18.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 2));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1038A', 'Capuchinho para trinco (capelinha)', 'OUTRO', '20x25x25mm; par: CAPA-1038A. Fonte: Catalogo AL Industria, pag. 18.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 2));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1038C', 'Capuchinho para trinco (ferradura)', 'OUTRO', '21x49mm; par: CAPA-1038C. Fonte: Catalogo AL Industria, pag. 18.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 2));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1101', 'Dobradiça superior com pino de inox', 'DOBRADICA', '51x129x7mm; par: CAPA-1101 (60x133mm). Obs: dimensões máximas do vidro 1000x2200mm ou 900x2600mm (larg x alt). Fonte: Catalogo AL Industria, pag. 18.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 2));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1101A', 'Dobradiça superior sem pino de inox', 'DOBRADICA', '51x129x7,2mm; par: CAPA-1101A (60x133mm). Mesma obs de vidro máximo do AL-1101. Fonte: Catalogo AL Industria, pag. 19.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 3));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1103', 'Dobradiça inferior para mola', 'DOBRADICA', '55x147mm; par: CAPA-1103 (59x150mm). Mesma obs de vidro máximo. Fonte: Catalogo AL Industria, pag. 19.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 3));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1103A', 'Dobradiça inferior com regulagem para pivô invertido', 'DOBRADICA', '55x147mm; par: CAPA-1103A (59x150mm). Fonte: Catalogo AL Industria, pag. 19.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 3));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1114', 'Dobradiça automática para box', 'DOBRADICA', '48x98x27x20mm; disponível apenas na Linha Tradicional. Obs: vidro máx. 600x1900mm, utilizando 2 peças. Fonte: Catalogo AL Industria, pag. 19.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 3));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1115', 'Dobradiça sem caimento para box', 'DOBRADICA', '48x98x27x20mm; disponível apenas na Linha Tradicional. Obs: vidro máx. 600x1900mm, 2 peças. Fonte: Catalogo AL Industria, pag. 19.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 3));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'CAPA-1116', 'Dobradiça lateral horizontal simples', 'DOBRADICA', '108x58mm; disponível apenas na Linha Capa. Obs: vidro máx. 1000x2200mm ou 900x2600mm. Fonte: Catalogo AL Industria, pag. 20.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 4));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1123', 'Dobradiça para vidro basculante com pino de inox', 'DOBRADICA', '58x54x25x37mm; par: CAPA-1123 (60x55mm). Obs: vidro máx. 800x700mm, 2 peças. Fonte: Catalogo AL Industria, pag. 20.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 4));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1125CR', 'Roldana excêntrica (nylon) com rolamento', 'ROLDANA', '30x20x16mm; par: CAPA-1125CR. Fonte: Catalogo AL Industria, pag. 20.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 4));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1125SR', 'Roldana excêntrica sem rolamento', 'ROLDANA', '30x20x16mm; par: CAPA-1125SR. Fonte: Catalogo AL Industria, pag. 20.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 4));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1130', 'Suporte para basculante e pivotante com pino de inox', 'OUTRO', '48x97x27x25mm; par: CAPA-1130 (55x105mm). Obs: vidro máx. 1000x800mm, 2 peças. Fonte: Catalogo AL Industria, pag. 20.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 4));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1131', 'Dobradiça maxin-ar V/V', 'DOBRADICA', '46x76x16x28mm; disponível apenas na Linha Tradicional. Obs: vidro máx. 800x700mm, 2 peças. Fonte: Catalogo AL Industria, pag. 21.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 5));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1132', 'Dobradiça maxin-ar V/A', 'DOBRADICA', '46x76x16x35x5mm; disponível apenas na Linha Tradicional. Obs: vidro máx. 800x700mm, 2 peças. Fonte: Catalogo AL Industria, pag. 21.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 5));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1201', 'Bucha para pivô de dobradiça', 'OUTRO', '19x62x7,2mm; par: CAPA-1201. Fonte: Catalogo AL Industria, pag. 21.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 5));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1201A', 'Bucha com pino de inox para pivô de dobradiça', 'OUTRO', '19x62x18x7mm; par: CAPA-1201A. Fonte: Catalogo AL Industria, pag. 21.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 5));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1203', 'Suporte para bandeira com ponto de giro para dobradiça superior', 'OUTRO', '131x98x7,2x25mm; par: CAPA-1203 (140x108mm). Obs: vidro máx. 2000x700mm, 2 peças. Fonte: Catalogo AL Industria, pag. 21.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 5));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1209', 'Facão simples para lateral e bandeira', 'OUTRO', '180x100x7,2x25x50mm; par: CAPA-1209 (180x110mm). Obs: vidro máx. 2000x700mm, 2 peças. Fonte: Catalogo AL Industria, pag. 22.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 6));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1230', 'Suporte para basculante e pivotante', 'OUTRO', '58x54x7,2x25x37mm; par: CAPA-1230 (60x55mm). Obs: vidro máx. 800x700mm, 2 peças. Fonte: Catalogo AL Industria, pag. 22.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 6));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1230A', 'Suporte para basculante e pivotante com trinco', 'OUTRO', '58x54x7,2x25x37mm; par: CAPA-1230A. Mesma obs de vidro máx.. Fonte: Catalogo AL Industria, pag. 22.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 6));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1231', 'Suporte com ponto de giro para basculante e pivotante', 'OUTRO', '48x97x7,2mm; par: CAPA-1231 (55x105mm). Obs: vidro máx. 1000x800mm, 2 peças. Fonte: Catalogo AL Industria, pag. 22.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 6));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1302', 'Suporte de canto', 'OUTRO', '48x48x25mm; par: CAPA-1302 (49x49mm). Obs: vidro máx. 1200x2200mm, 4 peças. Fonte: Catalogo AL Industria, pag. 22.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 6));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1304', 'Suporte sem miolo para união de dois vidros', 'OUTRO', '48x97mm; par: CAPA-1304 (55x105mm). Fonte: Catalogo AL Industria, pag. 23.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 7));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1306', 'Suporte com miolo para união de dois vidros', 'OUTRO', '48x97x7,2mm; par: CAPA-1306 (55x105mm). Fonte: Catalogo AL Industria, pag. 23.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 7));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1310', 'Suporte para união de dois ou três vidros em L', 'OUTRO', '98x98x25mm; par: CAPA-1310. Obs: vidro máx. 2000x700mm. Fonte: Catalogo AL Industria, pag. 23.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 7));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1315', 'Suporte para união de dois ou três vidros em L com batedeira', 'OUTRO', '98x98x3x8x25mm; par: CAPA-1315. Obs: vidro máx. 2000x700mm. Fonte: Catalogo AL Industria, pag. 23.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 7));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1316', 'Suporte para união de quatro vidros sem miolo', 'OUTRO', '98x98mm; par: CAPA-1316. Fonte: Catalogo AL Industria, pag. 23.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 7));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1329', 'Suporte de centro', 'OUTRO', '54x58x25x37mm; par: CAPA-1329 (55x60mm). Obs: vidro máx. 1000x1500mm, 4 peças. Fonte: Catalogo AL Industria, pag. 24.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 8));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1329P', 'Suporte de pressão para guarda-corpo', 'OUTRO', '45x45x25mm; disponível apenas na Linha Tradicional. Obs: vidro máx. 800x700mm, 4 peças. Fonte: Catalogo AL Industria, pag. 24.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 8));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1335', 'Trinco sem miolo', 'OUTRO', '54x58x25x18mm; par: CAPA-1335 (55x60mm). Fonte: Catalogo AL Industria, pag. 24.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 8));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1335C', 'Contratrinco para AL-1335', 'OUTRO', '54x58x25x16mm; par: CAPA-1335C. Fonte: Catalogo AL Industria, pag. 24.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 8));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1402', 'Suporte com batedor', 'OUTRO', '55x62x26x37mm; par: CAPA-1402 (55x60mm). Fonte: Catalogo AL Industria, pag. 24.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 8));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1504', 'Contrafechadura com recorte para AL-1520', 'FECHO', '50x98x43x75x9mm; par: CAPA-1504 (55x105mm). Fonte: Catalogo AL Industria, pag. 25.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 9));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1504A', 'Contrafechadura alvenaria para AL-1520', 'FECHO', '37x111mm; par: CAPA-1504A (45x112mm). Fonte: Catalogo AL Industria, pag. 25.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 9));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1510', 'Fechadura bico-de-papagaio com recorte para porta de correr', 'FECHO', '60x154x40x120x9mm; disponível apenas na Linha Tradicional. Fonte: Catalogo AL Industria, pag. 25.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 9));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1510JD', 'Fechadura bico-de-papagaio com recorte, direita, para janela', 'FECHO', '60x154mm; disponível apenas na Linha Tradicional. Fonte: Catalogo AL Industria, pag. 25.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 9));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1510JE', 'Fechadura bico-de-papagaio com recorte, esquerda, para janela', 'FECHO', '60x154mm; disponível apenas na Linha Tradicional. Fonte: Catalogo AL Industria, pag. 25.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 9));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1511', 'Contrafechadura com recorte para AL-1510', 'FECHO', '72x154x40x120x9mm; disponível apenas na Linha Tradicional. Fonte: Catalogo AL Industria, pag. 26.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 10));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1511A', 'Contrafechadura alvenaria para AL-1510, AL-1510JD e AL-1510JE', 'FECHO', '42x156mm; disponível apenas na Linha Tradicional. Fonte: Catalogo AL Industria, pag. 26.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 10));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1511JD', 'Contrafechadura com recorte para janela com fechadura AL-1510JD', 'FECHO', '72x154mm; disponível apenas na Linha Tradicional. Fonte: Catalogo AL Industria, pag. 26.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 10));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1519', 'Trinco inferior com miolo', 'FECHO', '97x48x43x75x9mm; disponível apenas na Linha Tradicional. Fonte: Catalogo AL Industria, pag. 26.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 10));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1520', 'Fechadura para porta de abrir', 'FECHO', '50x100x43x75x9mm; par: CAPA-1520 (55x105mm). Fonte: Catalogo AL Industria, pag. 26.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 10));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1523', 'Trinco central para basculante', 'FECHO', '59x54x37x25x30mm; par: CAPA-1523 (60x55mm). Fonte: Catalogo AL Industria, pag. 27.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 11));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1524', 'Contratrinco central para basculante', 'FECHO', '58x54x8x3x30mm; par: CAPA-1524 (60x55mm). Fonte: Catalogo AL Industria, pag. 27.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 11));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1531', 'Contrafechadura com aparador para AL-1520', 'FECHO', '62x100x43x75x9mm; par: CAPA-1531 (72x105mm). Fonte: Catalogo AL Industria, pag. 27.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 11));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1570', 'Fecho bate-fecha V/V', 'FECHO', '110x100x21x50x16mm; disponível apenas na Linha Tradicional. Obs: vidro máx. 650x800mm. Fonte: Catalogo AL Industria, pag. 27.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 11));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1571', 'Fecho bate-fecha V/A', 'FECHO', '52/22x100x27x50x16mm; disponível apenas na Linha Tradicional. Obs: vidro máx. 650x800mm. Fonte: Catalogo AL Industria, pag. 27.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 11));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1570B', 'Fecho bate-fecha blindex V/V', 'FECHO', '140x120x37x85x35x20mm; disponível apenas na Linha Tradicional. Obs: vidro máx. 650x800mm. Fonte: Catalogo AL Industria, pag. 28.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 12));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1571B', 'Fecho bate-fecha blindex V/V (variante compacta)', 'FECHO', '70/14x120mm; disponível apenas na Linha Tradicional. Obs: vidro máx. 650x800mm. Fonte: Catalogo AL Industria, pag. 28.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 12));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1570P', 'Mini fecho bate-fecha V/V', 'FECHO', '105x80x21x50mm; par: CAPA-1570P (108x83mm). Obs: vidro máx. 650x800mm. Fonte: Catalogo AL Industria, pag. 28.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 12));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1571P', 'Mini fecho bate-fecha V/A', 'FECHO', '60/12x80x27x50mm; par: CAPA-1571P (63/12x83mm). Fonte: Catalogo AL Industria, pag. 28.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 12));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1629A', 'Puxador (ferragem) com 18mm de diâmetro', 'OUTRO', '25x18mm; disponível apenas na Linha Tradicional. Fonte: Catalogo AL Industria, pag. 28.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 12));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1629B', 'Puxador (ferragem) com 25mm de diâmetro', 'OUTRO', '25x29mm; par: CAPA-1629B. Fonte: Catalogo AL Industria, pag. 29.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 13));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1629JA', 'Puxador (ferragem) com 18mm de diâmetro, variante JA', 'OUTRO', '18/7x29mm; disponível apenas na Linha Tradicional. Fonte: Catalogo AL Industria, pag. 29.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 13));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1629JB', 'Puxador (ferragem) com 25mm de diâmetro, variante JB', 'OUTRO', '22/8x25x29mm; par: CAPA-1629JB. Fonte: Catalogo AL Industria, pag. 29.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 13));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-1801', 'Chapinha para trinco basculante', 'OUTRO', '58x51mm; par: CAPA-1801. Fonte: Catalogo AL Industria, pag. 29.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 13));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-3206M', 'Contrafechadura de alvenaria para AL-3532M', 'FECHO', '38x88mm; disponível apenas na Linha Tradicional. Fonte: Catalogo AL Industria, pag. 29.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 13));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-3532M', 'Mini fechadura para janela de correr com furo', 'FECHO', '51x81x20x50mm; disponível apenas na Linha Tradicional. Fonte: Catalogo AL Industria, pag. 30.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 14));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-3536M', 'Contrafechadura com furo para AL-3532M', 'FECHO', '59x82x20x50mm; disponível apenas na Linha Tradicional. Fonte: Catalogo AL Industria, pag. 30.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 14));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-3206', 'Contrafechadura alvenaria para AL-3210, AL-3530 e AL-3532', 'FECHO', '48x115mm; par: CAPA-3206 (54x135mm). Fonte: Catalogo AL Industria, pag. 30.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 14));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-3210', 'Fechadura para porta de abrir com furo', 'FECHO', '62x112x37x85x35x20mm; par: CAPA-3210 (69x124mm). Fonte: Catalogo AL Industria, pag. 30.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 14));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-3211', 'Contrafechadura com aparador para AL-3210', 'FECHO', '76x112mm; par: CAPA-3211 (75x124mm). Fonte: Catalogo AL Industria, pag. 30.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 14));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-3212', 'Contrafechadura sem aparador para AL-3210', 'FECHO', '62x112mm; par: CAPA-3212 (69x124mm). Fonte: Catalogo AL Industria, pag. 31.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 15));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-3530', 'Fechadura para porta de correr com furo', 'FECHO', '62x112mm; par: CAPA-3530 (69x124mm). Fonte: Catalogo AL Industria, pag. 31.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 15));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-3532', 'Fechadura para janela de correr com furo', 'FECHO', '62x112mm; par: CAPA-3532 (69x124mm). Fonte: Catalogo AL Industria, pag. 31.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 15));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-3534', 'Contrafechadura com furo para AL-3530', 'FECHO', '76x112mm; par: CAPA-3534 (76x124mm). Fonte: Catalogo AL Industria, pag. 31.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 15));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-3536', 'Contrafechadura com furo para AL-3532', 'FECHO', '76x112mm; par: CAPA-3536 (76x124mm). Fonte: Catalogo AL Industria, pag. 31.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 15));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'CAPA-1510-11-DIR', 'Conjunto de fechadura maçaneta V/V, abertura direita', 'FECHO', '150x55x55mm; mesmo recorte da AL-1510. Atenção do catálogo: não utilizar a maçaneta CH 1510/11 em instalações com mola hidráulica e locais com alto fluxo. Fonte: Catalogo AL Industria, pag. 32.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 16));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'CAPA-1510-11-ESQ', 'Conjunto de fechadura maçaneta V/V, abertura esquerda', 'FECHO', '150x55x55mm; mesmo recorte da AL-1510. Mesma atenção sobre mola hidráulica. Fonte: Catalogo AL Industria, pag. 32.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 16));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'CAPA-1510-11A-DIR', 'Conjunto de fechadura maçaneta V/A, abertura direita', 'FECHO', '152x150x42x55mm; mesmo recorte da AL-1510. Mesma atenção sobre mola hidráulica. Fonte: Catalogo AL Industria, pag. 32.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 16));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'CAPA-1510-11A-ESQ', 'Conjunto de fechadura maçaneta V/A, abertura esquerda', 'FECHO', '150x152x55x42mm; mesmo recorte da AL-1510. Mesma atenção sobre mola hidráulica. Fonte: Catalogo AL Industria, pag. 32.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 16));

-- === Puxadores ===
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PARCO-500', 'Puxador polímero P Arco', 'PUXADOR', 'comprimento 500mm, entre centro 300mm. Acabamento: brilhante ou pintado natural fosco, branco, preto, bronze e bronze 1002. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PARCO-400', 'Puxador polímero P Arco', 'PUXADOR', 'comprimento 400mm, entre centro 300mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PARCO-300', 'Puxador polímero P Arco', 'PUXADOR', 'comprimento 300mm, entre centro 200mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PARCO-1FURO', 'Puxador polímero P Arco, 1 furo', 'PUXADOR', 'comprimento 190mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PI-20', 'Puxador redondo em inox', 'PUXADOR', 'comprimento 160mm, diâmetro 25mm. Acabamento: polido ou escovado. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PI-22', 'Puxador redondo em inox', 'PUXADOR', 'comprimento 500mm, entre centro 300mm, diâmetro 25mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PI-30', 'Puxador redondo em inox', 'PUXADOR', 'comprimento 500mm, entre centro 300mm, diâmetro 38mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PI-31', 'Puxador redondo em inox', 'PUXADOR', 'comprimento 800mm, entre centro 300mm, diâmetro 38mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PI-34', 'Puxador redondo em inox', 'PUXADOR', 'comprimento 1200mm, entre centro 500mm, diâmetro 38mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PI-35', 'Puxador redondo em inox', 'PUXADOR', 'comprimento 1500mm, entre centro 500mm, diâmetro 38mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PI-36', 'Puxador redondo em inox', 'PUXADOR', 'comprimento 300mm, entre centro 200mm, diâmetro 25mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PI-32', 'Puxador redondo em inox', 'PUXADOR', 'comprimento 400mm, entre centro 300mm, diâmetro 25mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PI-80', 'Puxador redondo em inox', 'PUXADOR', 'comprimento 800mm, entre centro 300mm, diâmetro 25mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PI-120', 'Puxador redondo em inox', 'PUXADOR', 'comprimento 1200mm, entre centro 500mm, diâmetro 25mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PI-150', 'Puxador redondo em inox', 'PUXADOR', 'comprimento 1500mm, entre centro 500mm, diâmetro 25mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PI-136', 'Puxador retangular em inox', 'PUXADOR', 'comprimento 300mm, entre centro 200mm, retangular 30x10mm. Acabamento: escovado. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PI-132', 'Puxador retangular em inox', 'PUXADOR', 'comprimento 400mm, entre centro 300mm, retangular 30x10mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PI-122', 'Puxador retangular em inox', 'PUXADOR', 'comprimento 500mm, entre centro 300mm, retangular 30x10mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PI-131', 'Puxador retangular em inox', 'PUXADOR', 'comprimento 800mm, entre centro 300mm, retangular 30x10mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PI-1120', 'Puxador retangular em inox', 'PUXADOR', 'comprimento 1200mm, entre centro 500mm, retangular 30x10mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PI-1150', 'Puxador retangular em inox', 'PUXADOR', 'comprimento 1500mm, entre centro 500mm, retangular 30x10mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PAL-376', 'Puxador redondo em alumínio', 'PUXADOR', 'comprimento 300mm, entre centro 300mm, diâmetro 25mm. Acabamento: brilhante ou pintado natural fosco, branco, preto, bronze e bronze 1002. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PAL-374', 'Puxador redondo em alumínio', 'PUXADOR', 'comprimento 300mm, entre centro 300mm, diâmetro 25mm (variante 374, conforme catálogo). Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PAL-36', 'Puxador redondo em alumínio', 'PUXADOR', 'comprimento 300mm, entre centro 200mm, diâmetro 25mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PAL-32', 'Puxador redondo em alumínio', 'PUXADOR', 'comprimento 400mm, entre centro 300mm, diâmetro 25mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PAL-28', 'Puxador redondo em alumínio', 'PUXADOR', 'comprimento 500mm, entre centro 300mm, diâmetro 25mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PAL-50', 'Puxador redondo em alumínio', 'PUXADOR', 'comprimento 500mm, entre centro 300mm, diâmetro 38mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PAL-51', 'Puxador redondo em alumínio', 'PUXADOR', 'comprimento 800mm, entre centro 300mm, diâmetro 38mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PAL-54', 'Puxador redondo em alumínio', 'PUXADOR', 'comprimento 1200mm, entre centro 500mm, diâmetro 38mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PAL-55', 'Puxador redondo em alumínio', 'PUXADOR', 'comprimento 1500mm, entre centro 500mm, diâmetro 38mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PAL-80', 'Puxador redondo em alumínio', 'PUXADOR', 'comprimento 800mm, entre centro 300mm, diâmetro 25mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PAL-120', 'Puxador redondo em alumínio', 'PUXADOR', 'comprimento 1200mm, entre centro 500mm, diâmetro 25mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PAL-150', 'Puxador redondo em alumínio', 'PUXADOR', 'comprimento 1500mm, entre centro 500mm, diâmetro 25mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PAL-46', 'Puxador quadrado em alumínio', 'PUXADOR', 'comprimento 300mm, entre centro 200mm, quadrado 25x25mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PAL-42', 'Puxador quadrado em alumínio', 'PUXADOR', 'comprimento 400mm, entre centro 300mm, quadrado 25x25mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PAL-48', 'Puxador quadrado em alumínio', 'PUXADOR', 'comprimento 500mm, entre centro 300mm, quadrado 25x25mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PAL-480', 'Puxador quadrado em alumínio', 'PUXADOR', 'comprimento 800mm, entre centro 300mm, quadrado 25x25mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PAL-4120', 'Puxador quadrado em alumínio', 'PUXADOR', 'comprimento 1200mm, entre centro 500mm, quadrado 25x25mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PAL-4150', 'Puxador quadrado em alumínio', 'PUXADOR', 'comprimento 1500mm, entre centro 500mm, quadrado 25x25mm. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'PP-26', 'Puxador redondo em aço carbono', 'PUXADOR', 'comprimento 160mm, diâmetro 25mm. Acabamento: pintado natural fosco, branco, preto, bronze e bronze 1002. Fonte: Catalogo AL Industria, pag. 33.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 17));

-- === Linha de produto: kits de aluminio (perfis de secao, sem peso -- catalogo nao informa) ===
INSERT INTO product_lines (id, manufacturer_id, name, code, description, origin_type, status_code) VALUES
(10, 8, 'Kits de Aluminio AL Industria', 'AL-KITS', 'Kit Sacada sem Rolamento, Kit Pia 6/8mm, Kit Box 8mm, Kit Box Reto 8mm, Kit Engenharia 8mm e 10mm -- perfis de secao (sem peso informado no catalogo, so dimensoes de secao) mais os descontos/folgas de vao citados literalmente: Kit Pia: portas = vao - 40mm (pag.39). Kit Box / Kit Box Reto: fixo = vao - 55mm, porta = vao - 20mm (pag.40). Kit Engenharia 8mm: fixo = vao - 60mm, correr = vao - 20mm (pag.41). Kit Engenharia 10mm: fixo = vao - 65mm, correr = vao - 25mm (pag.41). Kit Sacada sem Rolamento: folga na altura = vao menor - 200mm; folga na largura = 30mm (15mm cada lateral) + 3mm por juncao de vidro; peso maximo do vidro 8mm+acessorios = 25kg/m2, vidro 10mm+acessorios = 30kg/m2 (pag.35). Estes descontos NAO foram carregados como formula_deductions porque nao ha typology/formula_version correspondente cadastrada ainda -- ficam documentados aqui e em docs/FONTES.md para uso futuro.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO');

INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITPIA-TRILHOSUP', 'Kit Pia 6/8mm - Trilho Superior', 'OUTRO', 'Secao (mm): largura 37,1mm, altura 22mm. Sem peso informado no catalogo. Fonte: Catalogo AL Industria, pag. 39.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 18));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITPIA-TRILHOINF', 'Kit Pia 6/8mm - Trilho Inferior', 'OUTRO', 'Secao (mm): largura 37,2mm, altura 8,2mm. Sem peso informado no catalogo. Fonte: Catalogo AL Industria, pag. 39.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 18));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITPIA-PERFILLAT', 'Kit Pia 6/8mm - Perfil Lateral', 'OUTRO', 'Secao (mm): largura 39,8mm, altura 12,6mm. Sem peso informado no catalogo. Fonte: Catalogo AL Industria, pag. 39.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 18));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITPIA-LEITO', 'Kit Pia 6/8mm - Leito', 'OUTRO', 'Secao (mm): largura 14,4mm, altura 33,6mm. Sem peso informado no catalogo. Fonte: Catalogo AL Industria, pag. 39.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 18));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITBOX-TRILHOSUP', 'Kit Box 8mm - Trilho Superior', 'OUTRO', 'Secao (mm): largura 53,8mm, raio 49,6mm. Sem peso informado no catalogo. Fonte: Catalogo AL Industria, pag. 40.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 19));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITBOX-CAPA', 'Kit Box 8mm - Capa', 'OUTRO', 'Secao (mm): largura 16,38mm, altura 50mm. Sem peso informado no catalogo. Fonte: Catalogo AL Industria, pag. 40.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 19));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITBOX-GUIAINF', 'Kit Box 8mm - Guia Inferior (correr)', 'OUTRO', 'Secao (mm): largura 25,39mm, altura 22,2mm. Sem peso informado no catalogo. Fonte: Catalogo AL Industria, pag. 40.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 19));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITBOX-CLICK', 'Kit Box 8mm - Click', 'OUTRO', 'Secao (mm): largura 13mm, altura 5,85mm. Sem peso informado no catalogo. Fonte: Catalogo AL Industria, pag. 40.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 19));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITBOX-PERFILCANTO', 'Kit Box 8mm - Perfil Canto', 'OUTRO', 'Secao (mm): largura 19,72mm, altura 16,1mm. Sem peso informado no catalogo. Fonte: Catalogo AL Industria, pag. 40.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 19));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITBOX-PERFILU', 'Kit Box 8mm - Perfil U', 'OUTRO', 'Secao (mm): largura 20mm, altura 10,5mm. Sem peso informado no catalogo. Fonte: Catalogo AL Industria, pag. 40.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 19));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITBOXRETO-TRILHOSUP', 'Kit Box Reto 8mm - Trilho Superior', 'OUTRO', 'Secao (mm): largura 53,8mm, base 43,77mm. Sem peso informado no catalogo. Fonte: Catalogo AL Industria, pag. 40.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 19));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITENG8-CAPA', 'Kit Engenharia 8mm - Capa', 'OUTRO', 'Secao (mm): largura 17,7mm, altura 55,5mm. Sem peso informado no catalogo. Fonte: Catalogo AL Industria, pag. 41.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 20));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITENG8-TRILHOSUP', 'Kit Engenharia 8mm - Trilho Superior', 'OUTRO', 'Secao (mm): largura 41,86mm, altura 54,4mm. Sem peso informado no catalogo. Fonte: Catalogo AL Industria, pag. 41.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 20));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITENG8-GUIAINF', 'Kit Engenharia 8mm - Guia Inferior', 'OUTRO', 'Secao (mm): largura 31,5mm, altura 22,2mm. Sem peso informado no catalogo. Fonte: Catalogo AL Industria, pag. 41.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 20));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITENG8-CADEIRINHA', 'Kit Engenharia 8mm - Cadeirinha', 'OUTRO', 'Secao (mm): largura 21,4mm, altura 10mm. Sem peso informado no catalogo. Fonte: Catalogo AL Industria, pag. 41.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 20));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITENG8-TRANSPASSE', 'Kit Engenharia 8mm - Transpasse', 'OUTRO', 'Secao (mm): largura 14,2mm, altura 10mm. Sem peso informado no catalogo. Fonte: Catalogo AL Industria, pag. 41.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 20));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITENG8-PERFILUFIXO', 'Kit Engenharia 8mm - Perfil U Fixo', 'OUTRO', 'Secao (mm): largura 11,1mm, altura 22mm. Sem peso informado no catalogo. Fonte: Catalogo AL Industria, pag. 41.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 20));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITENG10-CAPA', 'Kit Engenharia 10mm - Capa', 'OUTRO', 'Secao (mm): largura 17,7mm, altura 55,5mm. Sem peso informado no catalogo. Fonte: Catalogo AL Industria, pag. 41.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 20));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITENG10-TRILHOSUP', 'Kit Engenharia 10mm - Trilho Superior', 'OUTRO', 'Secao (mm): largura 46,9mm, altura 60mm. Sem peso informado no catalogo. Fonte: Catalogo AL Industria, pag. 41.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 20));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITENG10-GUIAINF', 'Kit Engenharia 10mm - Guia Inferior', 'OUTRO', 'Secao (mm): largura 38,7mm, altura 24mm. Sem peso informado no catalogo. Fonte: Catalogo AL Industria, pag. 41.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (@al_first_ref + 20));
