-- 0017_al_industria_complemento.sql
-- Completa a extracao do catalogo AL Industria (technical_source_id=12, ver seed 0016):
-- os acessorios do Kit Sacada sem Rolamento (pagina 36, codigos de letra D-AC, com
-- quantidade por tamanho de kit) nao tinham sido carregados na primeira leva, e faltavam
-- algumas pecas de secao do Kit Box Reto e do Kit Engenharia 10mm (mesma pagina, mesma
-- fonte). As pecas AE-AJ do Kit Sacada nao tem dimensao numerica legivel na pagina (so
-- diagrama) -- cadastradas como PENDENTE em vez de inventar uma medida.

INSERT INTO source_references (technical_source_id, page_number, section_title, excerpt, extracted_by) VALUES
(12, 36, 'Catalogo AL Industria - Acessorios para Kit Sacada sem Rolamento', 'Tabela de itens e quantidades por tamanho de kit (2M/3M/4M/6M), codigos de letra D a AJ.', 'analise-catalogo-al-industria');
SET @al_ref_p36 = LAST_INSERT_ID();

-- === Acessorios do Kit Sacada (D-AC) ===
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-D', 'Parafuso cab. AMMSS PHS ARR TTM5 08x20', 'OUTRO', 'Quantidades por kit: 2M=10, 3M=12, 4M=14, 6M=18 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo D).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-E', 'Parafuso cab. AMMSS PHS ARR TTM5 08x25', 'OUTRO', 'Quantidades por kit: 2M=04, 3M=06, 4M=06, 6M=08 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo E).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-F', 'Porca quadrada M5x08', 'OUTRO', 'Quantidades por kit: 2M=10, 3M=14, 4M=18, 6M=25 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo F).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-G', 'Parafuso brocante 4,2x13', 'OUTRO', 'Quantidades por kit: 2M=10, 3M=14, 4M=18, 6M=18 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo G).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-I', 'Estacionamento pivô POM', 'OUTRO', 'Quantidades por kit: 2M=02, 3M=02, 4M=02, 6M=02 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo I).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-J', 'Estacionamento POM', 'OUTRO', 'Quantidades por kit: 2M=02, 3M=04, 4M=06, 6M=08 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo J).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-K', 'Disco - articulador de segurança', 'OUTRO', 'Quantidades por kit: 2M=08, 3M=12, 4M=16, 6M=24 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo K).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-L', 'Roldana sem rolamento sacada POM', 'ROLDANA', 'Quantidades por kit: 2M=08, 3M=12, 4M=16, 6M=24 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo L).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-M', 'Parafuso Allen s/cab M8x6 inox', 'OUTRO', 'Quantidades por kit: 2M=02, 3M=02, 4M=02, 6M=02 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo M).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-N', 'Parafuso Allen s/cab M8x10 inox', 'OUTRO', 'Quantidades por kit: 2M=02, 3M=02, 4M=02, 6M=02 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo N).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-O', 'Disco compl. POM', 'OUTRO', 'Quantidades por kit: 2M=12, 3M=18, 4M=24, 6M=36 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo O).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-P', 'Acabamento reto (porta deslizante) POM', 'OUTRO', 'Quantidades por kit: 2M=01, 3M=01, 4M=01, 6M=02 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo P).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-Q', 'Acabamento reto c/ aba direito (porta pivô) POM', 'OUTRO', 'Quantidades por kit: 2M=01, 3M=01, 4M=01, 6M=01 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo Q).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-R', 'Acabamento c/ aba esquerdo (porta pivô) POM', 'OUTRO', 'Quantidades por kit: 2M=01, 3M=01, 4M=01, 6M=01 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo R).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-S', 'Acabamento c/ esférico direito (porta deslizante) POM', 'OUTRO', 'Quantidades por kit: 2M=03, 3M=05, 4M=07, 6M=11 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo S).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-T', 'Acabamento c/ esférico esquerdo (porta deslizante) POM', 'OUTRO', 'Quantidades por kit: 2M=03, 3M=05, 4M=07, 6M=11 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo T).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-U', 'Tubo inox 3/8"', 'OUTRO', 'Comprimento por kit: 2M=250mm, 3M=350mm, 4M=400mm, 6M=430mm; 01 pç por kit. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo U).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-V', 'Bucha latão UZ trava porta', 'OUTRO', 'Quantidades por kit: 2M=02, 3M=02, 4M=02, 6M=02 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo V).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-W', 'Parafuso 3,8x25 zincado branco CH', 'OUTRO', 'Quantidades por kit: 2M=02, 3M=02, 4M=02, 6M=02 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo W).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-X', 'Parafuso Allen s/cab M6x6 inox', 'OUTRO', 'Quantidades por kit: 2M=02, 3M=02, 4M=02, 6M=02 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo X).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-Y', 'Suporte fixo', 'OUTRO', 'Quantidades por kit: 2M=01, 3M=01, 4M=01, 6M=01 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo Y).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-Z', 'Tope fixo direito', 'OUTRO', 'Quantidades por kit: 2M=01, 3M=01, 4M=01, 6M=01 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo Z).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-AA', 'Tope fixo esquerdo', 'OUTRO', 'Quantidades por kit: 2M=01, 3M=01, 4M=01, 6M=01 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo AA).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-AB', 'Tope móvel', 'OUTRO', 'Quantidades por kit: 2M=01, 3M=01, 4M=01, 6M=01 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo AB).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO accessories (manufacturer_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 'AL-KITSACADA-AC', 'Antiqueda POM', 'OUTRO', 'Quantidades por kit: 2M=01, 3M=02, 4M=02, 6M=02 pcs. Fonte: Catalogo AL Industria, pag. 36 (Acessorios para Kit Sacada sem Rolamento, codigo AC).', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);

-- === Perfis de secao adicionais (Kit Sacada AE-AJ + complemento Kit Box Reto / Kit Eng 10mm) ===
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITSACADA-LEITO', 'Kit Sacada sem Rolamento - Perfil Leito', 'OUTRO', 'Secao (mm): 8mm ou 10mm (duas versoes). Fonte: Catalogo AL Industria, pag. 36.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', @al_ref_p36);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITSACADA-ANCORAGEM', 'Kit Sacada sem Rolamento - Perfil Ancoragem', 'OUTRO', 'Secao (mm): sem dimensao numerica legivel na pagina. Fonte: Catalogo AL Industria, pag. 36.', 'ENCONTRADO_DOCUMENTO', 'PENDENTE', @al_ref_p36);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITSACADA-TRILHOS', 'Kit Sacada sem Rolamento - Perfil Trilho S (Superior)', 'OUTRO', 'Secao (mm): sem dimensao numerica legivel na pagina. Fonte: Catalogo AL Industria, pag. 36.', 'ENCONTRADO_DOCUMENTO', 'PENDENTE', @al_ref_p36);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITSACADA-TRILHOI', 'Kit Sacada sem Rolamento - Perfil Trilho I (Inferior)', 'OUTRO', 'Secao (mm): sem dimensao numerica legivel na pagina. Fonte: Catalogo AL Industria, pag. 36.', 'ENCONTRADO_DOCUMENTO', 'PENDENTE', @al_ref_p36);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITSACADA-ACAB45ABA', 'Kit Sacada sem Rolamento - Acabamento 45 graus com aba', 'OUTRO', 'Secao (mm): sem dimensao numerica legivel na pagina. Fonte: Catalogo AL Industria, pag. 36.', 'ENCONTRADO_DOCUMENTO', 'PENDENTE', @al_ref_p36);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITSACADA-ACAB45LISO', 'Kit Sacada sem Rolamento - Acabamento 45 graus liso', 'OUTRO', 'Secao (mm): sem dimensao numerica legivel na pagina. Fonte: Catalogo AL Industria, pag. 36.', 'ENCONTRADO_DOCUMENTO', 'PENDENTE', @al_ref_p36);
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITBOXRETO-CAPA', 'Kit Box Reto 8mm - Capa', 'OUTRO', 'Secao (mm): largura 16,38mm, altura 50mm. Fonte: Catalogo AL Industria, pag. 40.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (SELECT id FROM source_references WHERE technical_source_id=12 AND page_number=40 LIMIT 1));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITBOXRETO-GUIAINF', 'Kit Box Reto 8mm - Guia Inferior (correr)', 'OUTRO', 'Secao (mm): largura 23,22mm, altura 22,2mm. Fonte: Catalogo AL Industria, pag. 40.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (SELECT id FROM source_references WHERE technical_source_id=12 AND page_number=40 LIMIT 1));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITBOXRETO-CLICK', 'Kit Box Reto 8mm - Click', 'OUTRO', 'Secao (mm): largura 13mm, altura 5,85mm. Fonte: Catalogo AL Industria, pag. 40.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (SELECT id FROM source_references WHERE technical_source_id=12 AND page_number=40 LIMIT 1));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITBOXRETO-PERFILCANTO', 'Kit Box Reto 8mm - Perfil Canto', 'OUTRO', 'Secao (mm): largura 19,72mm, altura 16,1mm. Fonte: Catalogo AL Industria, pag. 40.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (SELECT id FROM source_references WHERE technical_source_id=12 AND page_number=40 LIMIT 1));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITBOXRETO-PERFILU', 'Kit Box Reto 8mm - Perfil U', 'OUTRO', 'Secao (mm): largura 20mm, altura 10,5mm. Fonte: Catalogo AL Industria, pag. 40.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (SELECT id FROM source_references WHERE technical_source_id=12 AND page_number=40 LIMIT 1));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITENG10-CADEIRINHA', 'Kit Engenharia 10mm - Cadeirinha', 'OUTRO', 'Secao (mm): largura 24mm, altura 14,5mm. Fonte: Catalogo AL Industria, pag. 41.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (SELECT id FROM source_references WHERE technical_source_id=12 AND page_number=41 LIMIT 1));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITENG10-TRANSPASSE', 'Kit Engenharia 10mm - Transpasse', 'OUTRO', 'Secao (mm): largura 18,7mm, altura 12,5mm. Fonte: Catalogo AL Industria, pag. 41.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (SELECT id FROM source_references WHERE technical_source_id=12 AND page_number=41 LIMIT 1));
INSERT INTO profiles (manufacturer_id, product_line_id, code, name, category, description, origin_type, status_code, source_reference_id) VALUES (8, 10, 'KITENG10-PERFILUCAVALAO', 'Kit Engenharia 10mm - Perfil U Cavalão', 'OUTRO', 'Secao (mm): largura 15mm, altura 25mm. Fonte: Catalogo AL Industria, pag. 41.', 'ENCONTRADO_DOCUMENTO', 'CATALOGADO', (SELECT id FROM source_references WHERE technical_source_id=12 AND page_number=41 LIMIT 1));

-- === LINHA PORTAO (product_line_id=8): concluida por decisao explicita do usuario em
-- === 2026-08-16 ("nao precisa pesquisar linhas, use as referencias que tem"). A
-- === classificacao como Alcoa (feita em 0015, evidencia fraca: 2 de 8 codigos) fica
-- === definitiva -- decisao humana deliberada de nao buscar mais fontes, nao uma nova
-- === evidencia tecnica. Os 6 codigos sem correspondencia no indice Alcoa (PC-027,
-- === 25-517, LB-072, TRD-1", TRG-2X1, GS-034) continuam com peso PENDENTE porque
-- === nenhuma fonte ja extraida traz esse dado -- decidir nao pesquisar mais nao cria
-- === um peso que nao existe nos documentos que temos.
UPDATE product_lines SET
description = CONCAT(description, ' | Classificacao concluida por decisao explicita do usuario em 2026-08-16: aceita como definitiva com a evidencia ja levantada (2 de 8 codigos), sem nova pesquisa. Os 6 perfis sem correspondencia no indice Alcoa continuam com peso PENDENTE -- decisao de concluir a identificacao do fabricante nao supre dado de peso que nenhuma fonte ja extraida contem.')
WHERE id = 8;
