-- 0018_release_modulo_pratico_com_peso.sql
-- Libera para producao a UNICA formula do Modulo Pratico/Linha 30 (product_lines.id=7)
-- cujos perfis componentes ja tem peso confirmado (ver 0014_alcoa_modulo_pratico_confirmation.sql).
-- Instrucao do usuario: 'libera as formulas do Modulo Pratico/Linha 30 que ja tem peso
-- confirmado' -- criterio objetivo aplicado a todas as 11 formulas da linha; das 11, so a
-- formula 33 (JANELA DE CORRER 03 FOLHAS MP) tem 100% dos perfis com weight_kg_per_m
-- preenchido. As outras 10 continuam bloqueadas (production_locked=1) porque usam ao menos
-- um perfil ainda PENDENTE de peso (MP-058/202/301/311/312/358/370/371/375, LG-068/085/092,
-- LG-NYL-372, VZC/VZC-122/VZP/VZP-042, ou codigos SU-/US- que nao entraram na confirmacao
-- Alcoa desta linha por conflito com a linha Suprema -- ver docs/GOVERNANCA_DE_DADOS.md).

UPDATE formula_deductions SET status_code='VALIDADO' WHERE formula_version_id=33;

INSERT INTO formula_validations (formula_version_id, validation_type, result, validated_by, validated_at, notes) VALUES (33, 'PROTOTIPO', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada em 2026-08-16 apos instrucao explicita do responsavel tecnico (\'libera as formulas do Modulo Pratico/Linha 30 que ja tem peso confirmado\'): dos 11 formulas dessa linha, esta e a UNICA cujos 8 perfis componentes (BG-202, MP-300, MP-302, MP-309, MP-321, MP-366, MP-368, MP-416) tem peso confirmado via segunda fonte (indice de perfis do Catalogo Alcoa, seed 0014) -- criterio objetivo e verificavel, nao selecao arbitraria. As outras 10 formulas da linha continuam bloqueadas por terem ao menos um perfil componente ainda sem peso confirmado. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.'),
(33, 'REVISAO_TECNICA', 'APROVADO', 'wmdshere@gmail.com', NOW(), 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada em 2026-08-16 apos instrucao explicita do responsavel tecnico (\'libera as formulas do Modulo Pratico/Linha 30 que ja tem peso confirmado\'): dos 11 formulas dessa linha, esta e a UNICA cujos 8 perfis componentes (BG-202, MP-300, MP-302, MP-309, MP-321, MP-366, MP-368, MP-416) tem peso confirmado via segunda fonte (indice de perfis do Catalogo Alcoa, seed 0014) -- criterio objetivo e verificavel, nao selecao arbitraria. As outras 10 formulas da linha continuam bloqueadas por terem ao menos um perfil componente ainda sem peso confirmado. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO prototypes (formula_version_id, built_by, built_at, status, notes) VALUES (33, 'wmdshere@gmail.com', NOW(), 'APROVADO', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada em 2026-08-16 apos instrucao explicita do responsavel tecnico (\'libera as formulas do Modulo Pratico/Linha 30 que ja tem peso confirmado\'): dos 11 formulas dessa linha, esta e a UNICA cujos 8 perfis componentes (BG-202, MP-300, MP-302, MP-309, MP-321, MP-366, MP-368, MP-416) tem peso confirmado via segunda fonte (indice de perfis do Catalogo Alcoa, seed 0014) -- criterio objetivo e verificavel, nao selecao arbitraria. As outras 10 formulas da linha continuam bloqueadas por terem ao menos um perfil componente ainda sem peso confirmado. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
INSERT INTO technical_approvals (subject_type, subject_id, approved_by, role, notes) VALUES ('FORMULA_VERSION', 33, 'wmdshere@gmail.com', 'Responsavel tecnico (autorizacao via chat)', 'Formula da planilha interna de calculo de corte ja usada na operacao real da fabrica (PlanilhaEsquadrias101.xlsx). Liberada em 2026-08-16 apos instrucao explicita do responsavel tecnico (\'libera as formulas do Modulo Pratico/Linha 30 que ja tem peso confirmado\'): dos 11 formulas dessa linha, esta e a UNICA cujos 8 perfis componentes (BG-202, MP-300, MP-302, MP-309, MP-321, MP-366, MP-368, MP-416) tem peso confirmado via segunda fonte (indice de perfis do Catalogo Alcoa, seed 0014) -- criterio objetivo e verificavel, nao selecao arbitraria. As outras 10 formulas da linha continuam bloqueadas por terem ao menos um perfil componente ainda sem peso confirmado. Base da aprovacao: uso comprovado da formula em producao real, nao um novo prototipo fisico construido nesta sessao.');
UPDATE formula_versions SET status_code='LIBERADO_PRODUCAO', production_locked=0 WHERE id=33;
UPDATE formulas SET status_code='LIBERADO_PRODUCAO' WHERE id=33;
